# Languages
brew 'deno'
brew 'go'
brew 'node@22'
brew 'nushell'
brew 'openjdk'
brew 'pnpm'
brew 'python@3.14'
brew 'sqlite'
brew 'typst'
brew 'zsh'

# Tools
brew 'btop'
brew 'cargo-binstall'
brew 'curl'
brew 'cmake'
brew 'direnv'
brew 'ffmpeg'
brew 'gallery-dl'
brew 'gcc'
brew 'gh'
brew 'git'
brew 'git-lfs'
brew 'htop'
brew 'mongodb/brew/mongodb-community'
brew 'mongosh'
brew 'mprocs'
brew 'neofetch'
brew 'neovim'
brew 'openssl'
brew 'stow'
brew 'wget'
brew 'yt-dlp'

# Casks
cask '1password'
cask 'blender'
cask 'brave-browser'
cask 'discord'
# cask 'docker-desktop'
cask 'figma'
cask 'google-drive'
cask 'herd'
cask 'iina'
cask 'iterm2'
cask 'linear-linear'
cask 'modrinth'
cask 'mongodb-compass'
cask 'mos'
cask 'nordvpn'
# cask 'notion'
# cask 'obs'
cask 'plexamp'
# cask 'postman'
# cask 'qbittorrent'
cask 'raycast'
cask 'shottr'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'tableplus'
brew 'tw93/tap/mole'
# cask 'visual-studio-code'
# cask 'vlc'
cask 'zed'

# Fonts
cask 'font-0xproto-nerd-font'
cask 'font-hack-nerd-font'
cask 'font-inter'
cask 'font-lilex-nerd-font'
cask 'font-meslo-lg-nerd-font'
