"---------- XDG Directories ----------"

set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

"---------- Plugins ----------"

call plug#begin('$XDG_CONFIG_HOME/vim/plugged')        " Specify plugin directory

Plug 'ctrlpvim/ctrlp.vim'                              " CtrlP fuzzy search
Plug 'neoclide/coc.nvim', {'branch': 'release'}        " Autocompletion
Plug 'editorconfig/editorconfig-vim'                   " Import editor config
Plug 'gosukiwi/vim-atom-dark'                        " Atom dark color scheme
Plug 'joshdick/onedark.vim'                          " One dark color scheme
" Plug 'junegunn/limelight.vim'                        " Dim inactive lines
Plug 'arcticicestudio/nord-vim'                        " Nord color theme
Plug 'scrooloose/nerdtree'                             " NerdTree file browser
Plug 'sheerun/vim-polyglot'                            " Better syntax highlighting
Plug 'tpope/vim-vinegar'                               " Vinegar file browser
Plug 'godlygeek/tabular'                               " Character alignment
Plug 'itchyny/lightline.vim'                           " Statusline
Plug 'xuhdev/vim-latex-live-preview', { 'for': 'tex' } " Vim LaTeX preview

call plug#end()                                        " Initialize plugins

"---------- General ----------"

syntax on

set backspace=indent,eol,start                  "Make backspace perform like any other editor
let mapleader=','                               "Change default leader to a comma
let skip_defaults_vim=1                         "Disable defaults.vim
set viminfo=""                                  "Disable viminfo
set tabstop=4                                   "Set default tab width to 4
set shiftwidth=4                                "Set default shift width to 4
set expandtab                                   "Convert tabs to spaces (sorry)

"---------- Airline ----------"

"let g:airline_powerline_fonts=1                 "Enable powerline fonts
"let g:airline_skip_empty_sections = 1

"---------- Lightline config ----------"

set laststatus=2

"---------- Visuals ----------"

set t_Co=256                                    "Set the terminal color depth to 256
colorscheme nord                                "Change the default color scheme
set guifont=Operator\ Mono\ Book:h14            "Set default font face and size
set linespace=10                                "Set line spacing to a reasonable level
set number                                      "Enable line numbers
set guioptions-=e                               "Disable custom gui tabs
hi vertsplit guifg=bg guibg=bg                  "Change split background

set guioptions-=l                               "Disable left-hand scrollbars
set guioptions-=L                               "Disable left-hand scrollbars when split
set guioptions-=re                              "Disable right-hand scrollbars
set guioptions-=R                               "Disable right-hand scrollbars when split

"---------- Splits ----------"

set splitbelow                                  "Create horizontal splits below current window
set splitright                                  "Create vertical splits to the right of current window

"Shortcuts to switch window splits
nmap <C-H> <C-W><C-H>
nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>
nmap <C-L> <C-W><C-L>

"---------- Searching ----------"

set hlsearch                                    "Highlight search results
set incsearch                                   "Highlight search results whilst typing query

"---------- Mappings ----------"

nmap <Leader>ev :tabedit $MYVIMRC<cr>           "Quickly edit vimrc file
nmap <Leader>c :nohlsearch<cr>                  "Remove highlighting
nmap <Leader>ll :Limelight!!<cr>                "Enable limelight mode
nmap Q <nop>                                    "Disable Ex mode
nmap q: <nop>                                   "Disable commandline window


"COC config
let g:coc_global_extensions = [
  \ 'coc-snippets',
  \ 'coc-pairs',
  \ 'coc-tsserver',
  \ 'coc-eslint',
  \ 'coc-prettier',
  \ 'coc-rust-analyzer',
  \ 'coc-json',
  \ ]

"---------- Auto-Commands ----------"

"Automatically source the vimrc file on save
augroup autosourcing
  autocmd!
  autocmd BufWritePost $MYVIMRC source %
augroup end

"---------- Plugin Overrides ----------"

"/
"/ CtrlP
"/

"Exclude specific folders from results
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

nmap <D-p> :CtrlP<cr>                           "Allow the use of Cmd+P for CtrlP
nmap <D-r> :CtrlPBufTag<cr>                     "Search for tags
nmap <D-e> :CtrlPMRUFiles<cr>                   "Show recently used files

"/
"/ Nerd Tree
"/

let NERDTreeHijackNetrw = 0                     "Disallow Nerdtree from hijacking hyphen
nmap <C-t> :NERDTreeToggle<cr>                  "Add shortcut for nerd tree
